name: Publish deb package

on: push

jobs:

  build_deb:
    runs-on: panda-arc
    strategy:
      matrix:
        debug: [1,2,3,4,5,6,7,8,9,10]
        ubuntu_version:
          - 20.04
          - 22.04

    steps:
      - name: Install git
        run: sudo apt-get -qq update -y && sudo apt-get -qq install git -y

      - name: Check out
        uses: actions/checkout@v4

      - name: Build package
        working-directory: panda/debian
        run: echo ${{ matrix.debug }} && ./setup.sh Ubuntu ${{ matrix.ubuntu_version }}
